<?php

define('CASSANDRA_KEYSPACE', 'NoSQLBlog');
define('CASSANDRA_COLUMNFAMILY_BLOGENTRIES', 'BlogEntries');
define('CASSANDRA_COLUMNFAMILY_TAGSPOSTS', 'TaggedPosts');
define('CASSANDRA_COLUMNFAMILY_TAGALL', '__allposts__');
