<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
<head>
	<title>NoSQLBlog</title>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
</head>
<body>
	<div class="head">
		<?php echo $this->partial("Header.phtml");?>
	</div>
	<div class="content">
		<?php echo $this->placeholder("content");?>
	</div>
	<div class="footer">
		<?php echo $this->partial("Footer.phtml");?>
	</div>
</body>
</html>